name: totem_app
description: Aplicativo de autoatendimento para restaurante com integração Linx Empório
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  mobile_scanner: ^3.5.5
  # HTTP Client
  http: ^1.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Geração de UUID
  uuid: ^4.2.1
  
  # Cache de imagens
  cached_network_image: ^3.3.0
  
  # Ícones
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/carousel/
  # Assets (imagens locais se necessário)
  # assets:
  #   - assets/images/
  
  # Fontes customizadas se necessário
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
